### ISSUE TITLE
openai key leak

### ISSUE THREAD

**Issue by scotthaleen** [DARPA-CRITICALMAAS/sri-ta2#1]
https://github.com/DARPA-CRITICALMAAS/sri-ta2/blob/main/sessions/0000000/params.json#L1

You should probably rotate this key if you haven't already.

**Comment by frkl** [comment]
Key has been disabled. Thanks for pointing out!

**Comment by frkl** [comment]
Closing issue.

**Comment by frkl** [comment]
Closing issue.
